/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
static yyconst short int yy_acclist[153] =
    {   0,
       18,   18,   31,   29,   30,   28,   29,   30,   26,   30,
       27,   29,   30,   29,   30,   22,   29,   30,   23,   29,
       30,   13,   29,   30,   19,   29,   30,   20,   29,   30,
       18,   29,   30,   18,   29,   30,   21,   29,   30,   14,
       29,   30,   15,   29,   30,   14,   29,   30,   17,   29,
       30,   17,   29,   30,   17,   29,   30,   17,   29,   30,
       17,   29,   30,   17,   29,   30,   17,   29,   30,   17,
       29,   30,   17,   29,   30,   17,   29,   30,   17,   29,
       30,   17,   29,   30,   24,   29,   30,   29,   30,   25,
       29,   30,   14,   18,   18,   18,   17,   17,   17,    8,

       17,   17,   17,   10,   17,   17,   17,   17,   17,   17,
       16,   17,   17,    5,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,    7,   17,   11,   17,
        2,   17,   17,   17,    4,   17,   17,   17,   17,    9,
       17,   12,   17,   17,   17,    1,   17,    6,   17,   17,
        3,   17
    } ;

static yyconst short int yy_accept[86] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   14,   16,   19,
       22,   25,   28,   31,   34,   37,   40,   43,   46,   49,
       52,   55,   58,   61,   64,   67,   70,   73,   76,   79,
       82,   85,   88,   90,   93,   94,   95,   95,   96,   97,
       98,   99,  100,  102,  103,  104,  106,  107,  108,  109,
      110,  111,  112,  113,  114,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  125,  126,  127,  129,  131,  133,
      134,  135,  137,  138,  139,  140,  142,  144,  145,  146,
      148,  150,  151,  153,  153
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   20,   21,   22,   23,

       24,   25,   26,   25,   27,   25,   28,   29,   25,   30,
       31,   32,   25,   33,   34,   35,   36,   25,   25,   25,
       25,   25,   37,   38,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst short int yy_base[86] =
    {   0,
        0,    0,  106,  107,  107,  107,  107,   87,  107,  107,
      107,  107,   26,   30,   34,  107,   86,   85,   84,   79,
       76,    0,   68,   68,   67,   73,   75,   70,   69,   72,
       61,  107,   52,  107,  107,   36,   38,   42,   46,    0,
       67,   62,    0,   64,   51,    0,   52,   64,   53,   48,
       46,  107,   56,   52,    0,   54,   38,   48,   53,   47,
       47,   41,   42,   45,   46,   39,    0,    0,    0,   39,
       32,    0,   42,   39,   41,    0,    0,   30,   28,    0,
        0,   17,    0,  107,   41
    } ;

static yyconst short int yy_def[86] =
    {   0,
       84,    1,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   84,   84,   84,   84,   84,   84,   84,   84,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   84,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,    0,   84
    } ;

static yyconst short int yy_nxt[147] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   11,   12,
       11,   13,   11,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   22,   22,   25,   22,   22,   22,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   36,
       36,   37,   40,   38,   38,   37,   83,   39,   39,   36,
       36,   36,   36,   37,   82,   38,   38,   37,   65,   39,
       39,   66,   81,   80,   79,   78,   77,   76,   75,   74,
       73,   72,   71,   70,   69,   68,   67,   64,   63,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       51,   50,   49,   48,   47,   46,   45,   44,   43,   42,

       41,   35,   35,   35,   35,   84,    3,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84
    } ;

static yyconst short int yy_chk[147] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   13,
       13,   14,   85,   14,   14,   15,   82,   15,   15,   36,
       36,   37,   37,   38,   79,   38,   38,   39,   57,   39,
       39,   57,   78,   75,   74,   73,   71,   70,   66,   65,
       64,   63,   62,   61,   60,   59,   58,   56,   54,   53,
       51,   50,   49,   48,   47,   45,   44,   42,   41,   33,
       31,   30,   29,   28,   27,   26,   25,   24,   23,   21,

       20,   19,   18,   17,    8,    3,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
//#line 1 "Test.l"
#define INITIAL 0
//#line 2 "Test.l"
#define TEST_IN_FILE1 "C:\\temp\\test1.txt"
#define TEST_IN_FILE2 "C:\\temp\\test2.txt"
#define TEST_OUT_FILE1 "C:\\temp\\test1_321354177_311201974_lex.txt"
#define TEST_OUT_FILE2 "C:\\temp\\test2_321354177_311201974_lex.txt"
#include <stdio.h>
#include <stdlib.h>
#include "Header.h"
#define VECTOR_INIT_CAPACITY 4

#define VECTOR_INIT(vec) TokenVector vec; vector_init(&vec)
#define VECTOR_ADD(vec, item) vector_add(&vec, (void *) item)
#define VECTOR_SET(vec, id, item) vector_set(&vec, id, (void *) item)
#define VECTOR_GET(vec, type, id) (type) vector_get(&vec, id)
#define VECTOR_DELETE(vec, id) vector_delete(&vec, id)
#define VECTOR_TOTAL(vec) vector_total(&vec)
#define VECTOR_FREE(vec) vector_free(&vec)
 FILE* testOut;
 line = 1;
 int yywrap()
{ return 1; }




/* reserved words */
//#line 528 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

//#line 84 "Test.l"

//#line 681 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 85 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 107 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */

#define StasPrint(_out,_line,_yytext,_type) \
		fprintf(_out,"Token from type '"#_type"' was found at line: %d, lexeme: '%s'\n",_line,_yytext); \
		printf("Token from type '"#_type"' was found at line: %d, lexeme: '%s' |", _line, _yytext);
switch ( yy_act )
	{ /* beginning of action switch */
	case 1:
	YY_RULE_SETUP
	//#line 85 "Test.l"
	{
		StasPrint(testOut, line, yytext, ParEnd)
		create_and_store_token(yytext, ParEnd, line);	return ParEnd;}
		YY_BREAK
	case 2:
	YY_RULE_SETUP
	//#line 86 "Test.l"
	{ 
	StasPrint(testOut, line, yytext, Task)
	create_and_store_token(yytext, Task, line); return Task;}
		YY_BREAK
	case 3:
	YY_RULE_SETUP
	//#line 87 "Test.l"
	{ StasPrint(testOut, line, yytext, ParBegin)

	create_and_store_token(yytext, ParBegin, line); return ParBegin;}
		YY_BREAK
	case 4:
	YY_RULE_SETUP
	//#line 88 "Test.l"
	{ StasPrint(testOut, line, yytext, Begin)

	create_and_store_token(yytext, Begin, line); return Begin;}
		YY_BREAK
	case 5:
	YY_RULE_SETUP
	//#line 89 "Test.l"
	{ StasPrint(testOut, line, yytext, End)

	create_and_store_token(yytext, End, line); return End;}
		YY_BREAK
	case 6:
	YY_RULE_SETUP
	//#line 90 "Test.l"
	{ StasPrint(testOut, line, yytext, Integer)

	create_and_store_token(yytext, Integer, line); return Integer;}
		YY_BREAK
	case 7:
	YY_RULE_SETUP
	//#line 91 "Test.l"
	{ StasPrint(testOut, line, yytext, Real)

	create_and_store_token(yytext, Real, line); return Real;}
		YY_BREAK
	case 8:
	YY_RULE_SETUP
	//#line 92 "Test.l"
	{ StasPrint(testOut, line, yytext, Do)

	create_and_store_token(yytext, Do, line); return Do;}
		YY_BREAK
	case 9:
	YY_RULE_SETUP
	//#line 93 "Test.l"
	{ StasPrint(testOut, line, yytext, Until)

	create_and_store_token(yytext, Until, line); return Until;}
		YY_BREAK
	case 10:
	YY_RULE_SETUP
	//#line 94 "Test.l"
	{ StasPrint(testOut, line, yytext, Od)

	create_and_store_token(yytext, Od, line); return Od;}
		YY_BREAK
	case 11:
	YY_RULE_SETUP
	//#line 95 "Test.l"
	{ StasPrint(testOut, line, yytext, Send)

	create_and_store_token(yytext, Send, line); return Send;}
		YY_BREAK
	case 12:
	YY_RULE_SETUP
	//#line 96 "Test.l"
	{ StasPrint(testOut, line, yytext, Accept)

	create_and_store_token(yytext, Accept, line); return Accept;}
		YY_BREAK
	case 13:
	YY_RULE_SETUP
	//#line 97 "Test.l"
	{ StasPrint(testOut, line, yytext, arOp)

	create_and_store_token(yytext, arOp, line); return arOp;}
		YY_BREAK
	case 14:
	YY_RULE_SETUP
	//#line 98 "Test.l"
	{ 
		StasPrint(testOut, line, yytext, relOp)
	create_and_store_token(yytext, relOp, line); return relOp;}
		YY_BREAK
	case 15:
	YY_RULE_SETUP
	//#line 99 "Test.l"
	{ StasPrint(testOut, line, yytext, assign)

	create_and_store_token(yytext, assign, line); return assign;}
		YY_BREAK
	case 16:
	YY_RULE_SETUP
	//#line 100 "Test.l"
	{ StasPrint(testOut, line, yytext, OR)

	create_and_store_token(yytext, OR, line); return OR;}
		YY_BREAK
	case 17:
	YY_RULE_SETUP
	//#line 101 "Test.l"
	{ StasPrint(testOut, line, yytext, ID)

	create_and_store_token(yytext, ID, line); return ID;}
		YY_BREAK
	case 18:
	YY_RULE_SETUP
	//#line 102 "Test.l"
	{ StasPrint(testOut, line, yytext, Number)

	create_and_store_token(yytext, Number, line); return Number;}
		YY_BREAK
	case 19:
	YY_RULE_SETUP
	//#line 103 "Test.l"
	{ StasPrint(testOut, line, yytext, Colon)

	create_and_store_token(yytext, Colon, line); return Colon;}
		YY_BREAK
	case 20:
	YY_RULE_SETUP
	//#line 104 "Test.l"
	{ StasPrint(testOut, line, yytext, dot)

	create_and_store_token(yytext, dot, line); return dot;}
		YY_BREAK
	case 21:
	YY_RULE_SETUP
	//#line 105 "Test.l"
	{ StasPrint(testOut, line, yytext, SemiColon)

	create_and_store_token(yytext, SemiColon, line); return SemiColon;}
		YY_BREAK
	case 22:
	YY_RULE_SETUP
	//#line 106 "Test.l"
	{ StasPrint(testOut, line, yytext, OpenRBracket)

	create_and_store_token(yytext, OpenRBracket, line); return OpenRBracket;}
		YY_BREAK
	case 23:
	YY_RULE_SETUP
	//#line 107 "Test.l"
	{ StasPrint(testOut, line, yytext, CloseRBracket)

	create_and_store_token(yytext, CloseRBracket, line); return CloseRBracket;}
		YY_BREAK
	case 24:
	YY_RULE_SETUP
	//#line 108 "Test.l"
	{ StasPrint(testOut, line, yytext, OpenCBracket)

	create_and_store_token(yytext, OpenCBracket, line); return OpenCBracket;}
		YY_BREAK
	case 25:
	YY_RULE_SETUP
	//#line 109 "Test.l"
	{ StasPrint(testOut, line, yytext, EndCBracket)

	create_and_store_token(yytext, EndCBracket, line); return EndCBracket;}
		YY_BREAK
	case 26:
	YY_RULE_SETUP
	//#line 110 "Test.l"
	{line++;}
		YY_BREAK
	case 27:
	YY_RULE_SETUP
	//#line 111 "Test.l"
	{}
		YY_BREAK
	case 28:
	YY_RULE_SETUP
	//#line 112 "Test.l"
	{}
		YY_BREAK
	case 29:
	YY_RULE_SETUP
	//#line 113 "Test.l"
	{ fprintf(testOut,"The character '%s' at line: %d does not begin any legal token in the language.",yytext, line); 
	printf("The character '%s' at line: %d does not begin any legal token in the language.",yytext, line);
	create_and_store_token(yytext, 50, line); return 50; }
		YY_BREAK
	case 30:
	YY_RULE_SETUP
	//#line 114 "Test.l"
	ECHO;
	YY_BREAK
	//#line 922 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 85 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 85 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 84);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif

//#line 114 "Test.l"


void InitializeGrammer();

#pragma region TokenVector
void vector_init(TokenVector *v)
{
    v->capacity = VECTOR_INIT_CAPACITY;
    v->count = 0;
    v->items = malloc(sizeof(Token *) * v->capacity);
}

int vector_total(TokenVector *v)
{
    return v->count;
}

void vector_resize(TokenVector *v, int capacity)
{
    #ifdef DEBUG_ON
    printf("vector_resize: %d to %d\n", v->capacity, capacity);
    #endif

    void **items = realloc(v->items, sizeof(Token *) * capacity);
    if (items) {
        v->items = items;
        v->capacity = capacity;
    }
}

void vector_add(TokenVector *v, Token *item)
{
    if (v->capacity == v->count)
        vector_resize(v, v->capacity * 2);
    v->items[v->count++] = item;
}

void vector_set(TokenVector *v, int index, Token *item)
{
    if (index >= 0 && index < v->count)
        v->items[index] = item;
}

char *vector_get(TokenVector *v, int index)
{
    if (index >= 0 && index < v->count)
        return v->items[index];
    return NULL;
}

void vector_delete(TokenVector *v, int index)
{
int i = 0;
    if (index < 0 || index >= v->count)
        return;

    v->items[index] = NULL;
	
    for (i = 0; i < v->count - 1; i++) {
        v->items[i] = v->items[i + 1];
        v->items[i + 1] = NULL;
    }

    v->count--;

    if (v->count > 0 && v->count == v->capacity / 4)
        vector_resize(v, v->capacity / 2);
}

void vector_free(TokenVector *v)
{
    free(v->items);
}

void clear_vector()
{
	int i;
	for (i = 0; i < Tokens.count; i++)
	{
		free(Tokens.items[i]->a);
		free(Tokens.items[i]);
	}
	vector_free(&Tokens);
}
#pragma endregion
#pragma region SentenceVector
void vector_init2(Sentence *v)
{
	v->capacity = VECTOR_INIT_CAPACITY;
	v->count = 0;
	v->words = malloc(sizeof(Word *) * v->capacity);
}

int vector_total2(Sentence *v)
{
	return v->count;
}

void vector_resize2(Sentence *v, int capacity)
{
#ifdef DEBUG_ON
	printf("vector_resize: %d to %d\n", v->capacity, capacity);
#endif

	void **items = realloc(v->words, sizeof(Word *) * capacity);
	if (items) {
		v->words = items;
		v->capacity = capacity;
	}
}

void vector_add2(Sentence *v, Word *item)
{
	if (v->capacity == v->count)
		vector_resize(v, v->capacity * 2);
	v->words[v->count++] = item;
}

void vector_set2(Sentence *v, int index, Word *item)
{
	if (index >= 0 && index < v->count)
		v->words[index] = item;
}

char *vector_get2(Sentence *v, int index)
{
	if (index >= 0 && index < v->count)
		return v->words[index];
	return NULL;
}

void vector_delete2(Sentence *v, int index)
{
	int i = 0;
	if (index < 0 || index >= v->count)
		return;

	v->words[index] = NULL;

	for (i = 0; i < v->count - 1; i++) {
		v->words[i] = v->words[i + 1];
		v->words[i + 1] = NULL;
	}

	v->count--;

	if (v->count > 0 && v->count == v->capacity / 4)
		vector_resize(v, v->capacity / 2);
}

void vector_free2(Sentence *v)
{
	free(v->words);
}

void clear_vector2(Sentence *sentence)
{
	int i;
	for (i = 0; i < Tokens.count; i++)
	{
		free(Tokens.items[i]->a);
		free(Tokens.items[i]);
	}
	vector_free(sentence);
}
#pragma endregion 
int i = 0;
int maxi = -1;
#pragma region Huge Initialization
char* SetName(char* name, int i)
{
	int len = strlen(name);
	char* alocName = calloc(len, sizeof(char));
	strcpy(alocName, name);
	return alocName;
}
void Initialize_Sentences()
{
	int SentenceOptions;
	int i;
	index.Command = 0;
	index.Commands = 0;
	index.Condition = 0;
	index.Declaration = 0;
	index.Declarations = 0;
	index.Expression = 0;
	index.Param_List = 0;
	index.Program = 0;
	index.Task_Definition = 0;
	index.Task_Definitions = 0;

	TokenMap[ParBegin] = SetName("ParBegin", ParBegin);
	TokenMap[ParEnd] = SetName("ParEnd", ParEnd);
	TokenMap[Task] = SetName("Task", Task);
	TokenMap[Begin] = SetName("Begin", Begin);
	TokenMap[End] = SetName("End", End);
	TokenMap[Integer] = SetName("Integer", Integer);
	TokenMap[Real] = SetName("Real", Real);
	TokenMap[Do] = SetName("Do", Do);
	TokenMap[Until] = SetName("Until", Until);
	TokenMap[Od] = SetName("Od", Od);
	TokenMap[Send] = SetName("Send", Send);
	TokenMap[Accept] = SetName("Accept", Accept);
	TokenMap[arOp] = SetName("arOp", arOp);
	TokenMap[relOp] = SetName("relOp", relOp);
	TokenMap[add] = SetName("add", add);
	TokenMap[substract] = SetName("substract", substract);
	TokenMap[multiply] = SetName("multiply", multiply);
	TokenMap[devide] = SetName("devide", devide);
	TokenMap[lessthan] = SetName("lessthan", lessthan);
	TokenMap[morethan] = SetName("morethan", morethan);
	TokenMap[lessorequal] = SetName("lessorequal", lessorequal);
	TokenMap[moreorequal] = SetName("moreorequal", moreorequal);
	TokenMap[equal] = SetName("equal", equal);
	TokenMap[notequal] = SetName("notequal", notequal);
	TokenMap[ID] = SetName("ID", ID);
	TokenMap[Number] = SetName("Number", Number);
	TokenMap[Colon] = SetName("Colon", Colon);
	TokenMap[SemiColon] = SetName("SemiColon", SemiColon);
	TokenMap[OR] = SetName("OR", OR);
	TokenMap[assign] = SetName("assign", assign);
	TokenMap[dot] = SetName("dot", dot);
	TokenMap[OpenRBracket] = SetName("OpenRBracket", OpenRBracket);
	TokenMap[CloseRBracket] = SetName("CloseRBracket", CloseRBracket);
	TokenMap[OpenCBracket] = SetName("OpenCBracket", OpenCBracket);
	TokenMap[EndCBracket] = SetName("EndCBracket", EndCBracket);
	TokenMap[EmptyWord] = SetName("EmptyWord", EmptyWord);


	SentenceOptions = 1;
	Sentences[esProgram] = calloc(sizeof(Sentence), SentenceOptions);
	for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esProgram][i]);
	vector_add2(&Sentences[esProgram][0], Create_Word(ewtVariable, esTask_Definitions));
	vector_add2(&Sentences[esProgram][0], Create_Word(ewtTerm, SemiColon));
	vector_add2(&Sentences[esProgram][0], Create_Word(ewtTerm,ParBegin));
	vector_add2(&Sentences[esProgram][0], Create_Word(ewtVariable, esTask_List));
	vector_add2(&Sentences[esProgram][0], Create_Word(ewtTerm, ParEnd));
	CurrentWord = Sentences[esProgram][0].words[0];

	SentenceOptions = 1;
	Sentences[esTask_Definitions] = calloc(sizeof(Sentence), SentenceOptions);
	for (i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esTask_Definitions][i]);
	vector_add2(&Sentences[esTask_Definitions][0], Create_Word(ewtVariable, esTask_Definition));
	vector_add2(&Sentences[esTask_Definitions][0], Create_Word(ewtVariable, esTask_Definitions_));

	SentenceOptions = 2;
	Sentences[esTask_Definitions_] = calloc(sizeof(Sentence), SentenceOptions);
	for (i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esTask_Definitions_][i]);
	vector_add2(&Sentences[esTask_Definitions_][0], Create_Word(ewtTerm, SemiColon));
	vector_add2(&Sentences[esTask_Definitions_][0], Create_Word(ewtVariable, esTask_Definition));
	vector_add2(&Sentences[esTask_Definitions_][0], Create_Word(ewtVariable, esTask_Definitions_));
	vector_add2(&Sentences[esTask_Definitions_][1], Create_Word(ewtTerm,  EmptyWord));

	SentenceOptions = 1;
	Sentences[esTask_Definition] = calloc(sizeof(Sentence), SentenceOptions);
	for (i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esTask_Definition][i]);
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, Task));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, Begin));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtVariable, esDeclarations));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, OpenCBracket));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtVariable, esCommands));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, EndCBracket));
	vector_add2(&Sentences[esTask_Definition][0], Create_Word(ewtTerm, End));

	SentenceOptions = 1;
	Sentences[esDeclarations] = calloc(sizeof(Sentence), SentenceOptions);
	for (i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esDeclarations][i]);
	vector_add2(&Sentences[esDeclarations][0], Create_Word(ewtVariable, esDeclaration));
	vector_add2(&Sentences[esDeclarations][0], Create_Word(ewtVariable, esDeclarations_));


	SentenceOptions = 2;
	Sentences[esDeclarations_] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esDeclarations_][i]);
	vector_add2(&Sentences[esDeclarations_][0], Create_Word(ewtTerm, SemiColon));
	vector_add2(&Sentences[esDeclarations_][0], Create_Word(ewtVariable, esDeclarations));
	vector_add2(&Sentences[esDeclarations_][1], Create_Word(ewtTerm, EmptyWord));

	SentenceOptions = 2;
	Sentences[esDeclaration] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esDeclaration][i]);
	vector_add2(&Sentences[esDeclaration][0], Create_Word(ewtTerm, Integer));
	vector_add2(&Sentences[esDeclaration][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esDeclaration][1], Create_Word(ewtTerm, Real));
	vector_add2(&Sentences[esDeclaration][1], Create_Word(ewtTerm, ID));

	SentenceOptions = 1;
	Sentences[esTask_List] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esTask_List][i]);
	vector_add2(&Sentences[esTask_List][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esTask_List][0], Create_Word(ewtVariable, esTask_List_));

	SentenceOptions = 2;
	Sentences[esTask_List_] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esTask_List_][i]);
	vector_add2(&Sentences[esTask_List_][0], Create_Word(ewtTerm, OR));
	vector_add2(&Sentences[esTask_List_][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esTask_List_][0], Create_Word(ewtVariable, esTask_List_));
	vector_add2(&Sentences[esTask_List_][1], Create_Word(ewtTerm, EmptyWord));

	SentenceOptions = 1;
	Sentences[esCommands] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esCommands][i]);
	vector_add2(&Sentences[esCommands][0], Create_Word(ewtVariable, esCommand));
	vector_add2(&Sentences[esCommands][0], Create_Word(ewtVariable, esCommands_));

	SentenceOptions = 2;
	Sentences[esCommands_] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esCommands_][i]);
	vector_add2(&Sentences[esCommands_][0], Create_Word(ewtTerm, SemiColon));
	vector_add2(&Sentences[esCommands_][0], Create_Word(ewtTerm, esCommand));
	vector_add2(&Sentences[esCommands_][0], Create_Word(ewtVariable, esCommands_));
	vector_add2(&Sentences[esCommands_][1], Create_Word(ewtTerm, EmptyWord));

	SentenceOptions = 5;
	Sentences[esCommand] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esCommand][i]);
	vector_add2(&Sentences[esCommand][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCommand][0], Create_Word(ewtTerm, equal));
	vector_add2(&Sentences[esCommand][0], Create_Word(ewtVariable, esExpression));
	vector_add2(&Sentences[esCommand][1], Create_Word(ewtTerm, Do));
	vector_add2(&Sentences[esCommand][1], Create_Word(ewtVariable, esCommand));
	vector_add2(&Sentences[esCommand][1], Create_Word(ewtTerm, Until));
	vector_add2(&Sentences[esCommand][1], Create_Word(ewtVariable, esCondition));
	vector_add2(&Sentences[esCommand][1], Create_Word(ewtTerm, Od));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, Send));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, dot));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, OpenRBracket));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtVariable, esParam_List));
	vector_add2(&Sentences[esCommand][2], Create_Word(ewtTerm, CloseRBracket));

	vector_add2(&Sentences[esCommand][3], Create_Word(ewtTerm, Accept));
	vector_add2(&Sentences[esCommand][3], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCommand][3], Create_Word(ewtTerm, OpenRBracket));
	vector_add2(&Sentences[esCommand][3], Create_Word(ewtVariable, esDeclarations));
	vector_add2(&Sentences[esCommand][3], Create_Word(ewtTerm, CloseRBracket));

	vector_add2(&Sentences[esCommand][4], Create_Word(ewtTerm, Begin));
	vector_add2(&Sentences[esCommand][4], Create_Word(ewtVariable, esDeclarations));
	vector_add2(&Sentences[esCommand][4], Create_Word(ewtTerm, OpenCBracket));
	vector_add2(&Sentences[esCommand][4], Create_Word(ewtVariable, esCommands));
	vector_add2(&Sentences[esCommand][4], Create_Word(ewtTerm, EndCBracket));
	vector_add2(&Sentences[esCommand][4], Create_Word(ewtTerm, End));

	SentenceOptions = 1;
	Sentences[esParam_List] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esParam_List][i]);
	vector_add2(&Sentences[esParam_List][0], Create_Word(ewtVariable, esExpression));
	vector_add2(&Sentences[esParam_List][0], Create_Word(ewtVariable, esParam_List_));

	SentenceOptions = 2;
	Sentences[esParam_List_] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esParam_List_][i]);
	vector_add2(&Sentences[esParam_List_][0], Create_Word(ewtTerm, SemiColon));
	vector_add2(&Sentences[esParam_List_][0], Create_Word(ewtVariable, esParam_List));
	vector_add2(&Sentences[esParam_List_][1], Create_Word(ewtTerm, EmptyWord));

	SentenceOptions = 6;
	Sentences[esExpression] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esExpression][i]);
	vector_add2(&Sentences[esExpression][0], Create_Word(ewtTerm, Number));
	vector_add2(&Sentences[esExpression][1], Create_Word(ewtTerm, Number));
	vector_add2(&Sentences[esExpression][2], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esExpression][3], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esExpression][3], Create_Word(ewtTerm, arOp));
	vector_add2(&Sentences[esExpression][3], Create_Word(ewtVariable, esExpression));
	/*vector_add2(&Sentences[esExpression][4], Create_Word(ewtTerm, Number));
	vector_add2(&Sentences[esExpression][4], Create_Word(ewtVariable, esExpression));
	vector_add2(&Sentences[esExpression][5], Create_Word(ewtTerm, Number));
	vector_add2(&Sentences[esExpression][5], Create_Word(ewtVariable, esExpression));*/

	SentenceOptions = 1;
	Sentences[esCondition] = calloc(sizeof(Sentence), SentenceOptions);
	 for( i = 0; i < SentenceOptions; i++) vector_init2(&Sentences[esCondition][i]);
	vector_add2(&Sentences[esCondition][0], Create_Word(ewtTerm, OpenRBracket));
	vector_add2(&Sentences[esCondition][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCondition][0], Create_Word(ewtTerm, relOp));
	vector_add2(&Sentences[esCondition][0], Create_Word(ewtTerm, ID));
	vector_add2(&Sentences[esCondition][0], Create_Word(ewtTerm, CloseRBracket));

}
#pragma endregion


char* back_token()
{
	if (i > 0)
	{
		i--;
		return vector_get(&Tokens, i);
	}
	return NULL;
}

char* next_token()
{
	int type;
	i++;
	if (Tokens.count < i)
	{
		type = yylex();

		if (!type)
		{
			return NULL;
		}
		maxi = i;
	}

	return vector_get(&Tokens, i-1);
}

void create_and_store_token(char* s, int type, int line)
{
	int Len = (strlen(s) + 1);

	Token* t = (Token*)calloc(1, sizeof(Token));
	t->type = type;
	t->line = line;
	t->a = (char*)calloc(Len, sizeof(char));
	strcpy(t->a, s);
	vector_add(&Tokens, t);
}

// assignment 2
Word* Create_Word(int type, int tokenType)
{
	Word* t = (Word*)calloc(1, sizeof(Word));
	t->type = type;
	t->tokenType = tokenType;
	return t;
}


int Get_Next_Expected_Token()
{
	switch (SentenceIndex)
	{
	case esCommand: { return fCommand();   }
	case esCommands: { return fCommands();   }
	case esCommands_: { return fCommands_();   }
	case esCondition: { return fCondition();   }
	case esDeclaration: { return fDeclaration();   }
	case esDeclarations: { return fDeclarations();   }
	case esDeclarations_: { return fDeclarations_();   }
	case esExpression: { return fExpression();	  }
	case esParam_List: { return fParam_List();	  }
	case esParam_List_: { return fParam_List_();   }
	case esProgram: { return fProgram();   }
	case esTask_Definition: { return fTask_Definition();   }
	case esTask_Definitions: { return fTask_Definitions();   }
	case esTask_Definitions_: { return fTask_Definitions_();   }
	case esTask_List: { return fTask_List();   }
	case esTask_List_: { return fTask_List_();   }
	default:break;
	}
}
int Match(int type, int* a_index,int SentenceOptions)
{
	int i_option;
	int c_option=-1;
	int i_word;
	int returnValue;
	//SentenceIndex = type;

	// find the correct option
	for (i_option = 0; i_option < SentenceOptions; i_option++)
	{
		for (i_word = 0; i_word < Sentences[type][i_option].count; i_word++)
		{
			if (Sentences[type][i_option].words[(*a_index)]->type == ewtTerm)
			{
				if (Sentences[type][i_option].words[(*a_index)++]->tokenType == token->type)
				{
					c_option = i_option; break;
				}
			}
			else
			{
				switch (Sentences[type][i_option].words[(*a_index)]->tokenType)
				{
				case esCommand: { index.Command = 0; /*----------------------*/	option.Command = 0; /*------------*/ returnValue = fCommand(); if (returnValue != -1) c_option=returnValue; break; }
				case esCommands: { index.Commands = 0; /*--------------------*/	option.Commands = 0; /*-----------*/ returnValue = fCommands(); if (returnValue != -1) c_option=returnValue;  break; }
				case esCommands_: { index.Commands_ = 0; /*------------------*/	option.Commands_ = 0; /*----------*/ returnValue = fCommands_(); if (returnValue != -1) c_option=returnValue;  break; }
				case esCondition: { index.Condition = 0; /*------------------*/	option.Condition = 0; /*----------*/ returnValue = fCondition(); if (returnValue != -1) c_option=returnValue;  break; }
				case esDeclaration: { index.Declaration = 0; /*--------------*/	option.Declaration = 0; /*--------*/ returnValue = fDeclaration(); if (returnValue != -1) c_option=returnValue; break; }
				case esDeclarations: { index.Declarations = 0; /*------------*/	option.Declarations = 0; /*-------*/ returnValue = fDeclarations(); if (returnValue != -1) c_option=returnValue;  break; }
				case esDeclarations_: { index.Declarations_ = 0; /*----------*/	option.Declarations_ = 0; /*------*/ returnValue = fDeclarations_(); if (returnValue!= -1) c_option=returnValue;  break;  }
				case esExpression: { index.Expression = 0; /*----------------*/	option.Expression = 0; /*---------*/ returnValue = fExpression(); if (returnValue !=-1) c_option=returnValue;   break; }
				case esParam_List: { index.Param_List = 0; /*----------------*/	option.Param_List = 0; /*---------*/ returnValue = fParam_List(); if (returnValue !=-1) c_option=returnValue;   break; }
				case esParam_List_: { index.Param_List_ = 0; /*--------------*/	option.Param_List_ = 0; /*--------*/ returnValue = fParam_List_(); if (returnValue != -1) c_option=returnValue;   break; }
				case esProgram: { index.Program = 0; /*----------------------*/	option.Program = 0; /*------------*/ returnValue = fProgram(); if (returnValue != -1) c_option=returnValue;  break; }
				case esTask_Definition: { index.Task_Definition = 0; /*------*/	option.Task_Definition = 0; /*----*/ returnValue = fTask_Definition(); if (returnValue != -1) c_option=returnValue;  break; }
				case esTask_Definitions: { index.Task_Definitions = 0; /*----*/	option.Task_Definitions = 0; /*---*/ returnValue = fTask_Definitions(); if (returnValue != -1) c_option=returnValue;  break; }
				case esTask_Definitions_: { index.Task_Definitions_ = 0; /*--*/	option.Task_Definitions_ = 0; /*--*/ returnValue = fTask_Definitions_(); if (returnValue != -1) c_option=returnValue;  break; }
				case esTask_List: { index.Task_List = 0; /*------------------*/	option.Task_List = 0; /*----------*/ returnValue = fTask_List(); if (returnValue != -1) c_option=returnValue;  break;  }
				case esTask_List_: { index.Task_List_ = 0; /*----------------*/	option.Task_List_ = 0; /*---------*/ returnValue = fTask_List_(); if (returnValue !=-1) c_option=returnValue;   break;  }
				default:break;
				}
				if (returnValue == -1)
					exit(0);
			}
		}
	}
	for (i_word = 0; i_word < Sentences[type][c_option].count; i_word++)
	{
		if (Sentences[type][c_option].words[(*a_index)]->type == ewtTerm)
		{
			if (Sentences[type][c_option].words[(*a_index)++]->tokenType == token->type)
				token = next_token();
			//return Sentences[type][fi].words[(*a_index)++]->tokenType;
		}
		else
		{
			switch (Sentences[type][c_option].words[(*a_index)]->tokenType)
			{
			case esCommand: { index.Command = 0; /*----------------------*/	option.Command = 0; /*------------*/ returnValue = fCommand();			/**/ break; }
			case esCommands: { index.Commands = 0; /*--------------------*/	option.Commands = 0; /*-----------*/ returnValue = fCommands();			/**/ break; }
			case esCommands_: { index.Commands_ = 0; /*------------------*/	option.Commands_ = 0; /*----------*/ returnValue = fCommands_();		/**/ break; }
			case esCondition: { index.Condition = 0; /*------------------*/	option.Condition = 0; /*----------*/ returnValue = fCondition();		/**/ break; }
			case esDeclaration: { index.Declaration = 0; /*--------------*/	option.Declaration = 0; /*--------*/ returnValue = fDeclaration();		/**/ break; }
			case esDeclarations: { index.Declarations = 0; /*------------*/	option.Declarations = 0; /*-------*/ returnValue = fDeclarations();		/**/ break; }
			case esDeclarations_: { index.Declarations_ = 0; /*----------*/	option.Declarations_ = 0; /*------*/ returnValue = fDeclarations_();	/**/ break;  }
			case esExpression: { index.Expression = 0; /*----------------*/	option.Expression = 0; /*---------*/ returnValue = fExpression();		/**/ break; }
			case esParam_List: { index.Param_List = 0; /*----------------*/	option.Param_List = 0; /*---------*/ returnValue = fParam_List();		/**/ break; }
			case esParam_List_: { index.Param_List_ = 0; /*--------------*/	option.Param_List_ = 0; /*--------*/ returnValue = fParam_List_();		/**/ break; }
			case esProgram: { index.Program = 0; /*----------------------*/	option.Program = 0; /*------------*/ returnValue = fProgram();			/**/ break; }
			case esTask_Definition: { index.Task_Definition = 0; /*------*/	option.Task_Definition = 0; /*----*/ returnValue = fTask_Definition();	/**/ break; }
			case esTask_Definitions: { index.Task_Definitions = 0; /*----*/	option.Task_Definitions = 0; /*---*/ returnValue = fTask_Definitions(); /**/ break; }
			case esTask_Definitions_: { index.Task_Definitions_ = 0; /*--*/	option.Task_Definitions_ = 0; /*--*/ returnValue = fTask_Definitions_();/**/ break; }
			case esTask_List: { index.Task_List = 0; /*------------------*/	option.Task_List = 0; /*----------*/ returnValue = fTask_List();		/**/ break;  }
			case esTask_List_: { index.Task_List_ = 0; /*----------------*/	option.Task_List_ = 0; /*---------*/ returnValue = fTask_List_();		/**/ break;  }
			default:break;
			}
			// broke from switch
			//SentenceIndex = type;
		}
	}
	token = next_token();
	if (token == NULL) return 0;
}
int SentenceIndex = esProgram;

void main()
{
 FILE* testIn; 
 Token* token;
 int choice;
 int ExpectedType;

 Initialize_Sentences();
 vector_init(&Tokens);
 printf("Legit too autistic to get a job, so i check compilation homework\n");

 printf("choose file: 1 or 2:\n");
 scanf("%d",&choice);
 
 if (choice == 1)
 {
	fopen_s(&testIn, TEST_IN_FILE1, "r");
	fopen_s(&testOut, TEST_OUT_FILE1, "w");
 }
 else if (choice == 2)
 {
	fopen_s(&testIn, TEST_IN_FILE2, "r");
	fopen_s(&testOut, TEST_OUT_FILE2, "w");
 }
 else
 {
	return;
 }
  
 yyin = testIn;
 yyout = testOut;

 fProgram();
// while ((token = next_token()) != NULL)
// {
//	 if (token == 50) continue;
//	 ExpectedType = Get_Next_Expected_Token();
//	 if (ExpectedType == token->type)
//	 {
//#define printGood(_expectedToken) \
//			printf(" Received token : '%s' as expected at line %d \n ", _expectedToken, line);
//		 printGood(TokenMap[ExpectedType])
//	 }
//	 else
//	 {
//#define printBad(_expectedToken,_receivedToken) \
//			printf(" !!Expected token '%s' at line %d; received '%s' \n", _expectedToken, line, _receivedToken);
//		 printBad(TokenMap[ExpectedType], TokenMap[token->type])
//	 }
// }
 
fclose(testIn);
fclose(testOut);

clear_vector();
system("pause");
}
